Provide blocking and async versions of `pixel_rgb` methods.
Univa/is31fl3731 pull request #1
Opened 2024-03-03 10:00 UTC by trepidacious

This also fixes an unsatisfied trait bound error.

Rename existing `pixel_rgb` methods to `pixel_rgb_blocking`, and update them to use `device.pixel_blocking` since async `device.pixel` is not available based on `I2C` constraints.

Add new `impl`s for async `pixel_rgb` methods, with async hal constraint on `I2C` to allow calling `device.pixel`.

2024-03-03 10:03 UTC, trepidacious commented
Note - I've tested the `Keybow2040` device on hardware, but not the other two affected devices. The changes are the same so I'd hope this would work.

2024-03-03 20:04 UTC, Univa requested changes
Thanks for the PR!

2024-03-03 20:04 UTC, Univa commented on src/devices.rs
> +#[cfg(feature = "keybow_2040")]
Since the `impl` block uses `embedded_hal_async`, this should also be gated by the `async` feature. Same with the other two affected devices.

```suggestion
#[cfg(all(feature = "keybow_2040", feature = "async"))]
```

2024-03-03 20:04 UTC, Univa commented on src/devices.rs
Since there are new `impl` blocks with different trait bounds, I think the `configure` methods for the affected devices should be moved into a new `impl` block that is free of trait bounds:

```diff
+#[cfg(feature = "keybow_2040")]
+impl<I2C> Keybow2040<I2C> {
+    pub fn configure(i2c: I2C) -> Self {
+        // ...
+    }
+}

impl<I2C, I2cError> Keybow2040<I2C>
where
    I2C: Write<Error = I2cError>,
{
-   pub fn configure(i2c: I2C) -> Self {
-       // ...
-   }

    // ...
}
```

This should allow users to call `configure` if their type implements `embedded_hal_async::i2c::I2c` but not `embedded_hal::blocking::i2c::Write`. This doesn't affect you if you're using `embassy-rp`, since the `embassy-rp::i2c::I2c` struct implements both, but it does affect other HALs (I came across problems with `embassy-stm32::i2c`, using DMA).

2024-03-07 08:49 UTC, trepidacious commented on src/devices.rs
> +#[cfg(feature = "keybow_2040")]
Done :)

2024-03-07 08:50 UTC, trepidacious commented on src/devices.rs
Done - I also noticed I'd left `_blocking` on the end of one of the non-blocking `pixel_rgb` functions, so I've fixed that too.

2024-03-07 16:10 UTC, merged